### ISSUE TITLE
Instructions could be more explicit about installing Bundler

### ISSUE THREAD

**Issue by neilernst** [wesabe/mesabe#1]
It says it's a prereq for OSX, but I think it might be easier if after install libcharguess, the instructions explicitly say "gem install bundler".

To set archflags, you could write "At the prompt, type export ARCHFLAGS=-arch=X86". Currently it looks like you append it to the bundle command.

Also, most of these commands should probably run sudo.

**Comment by precipice** [comment]
I agree. I'll make some changes.

**Comment by eventualbuddha** [comment]
The archflags thing is better now. Thanks!
