### ISSUE TITLE
Error with mysql step of bundle install

### ISSUE THREAD

**Issue by tommyvernieri** [wesabe/mesabe#10]
I was stuck on the `bundle install` step of the PFC instructions. I ended up installing libmysqlclient-dev to get past it. I'm not sure if that was right or not, but it seemed to work. I'm running a clean install of Ubuntu 10.04.

```
sudo aptitude install libmysqlclient-dev
```

Original output from `bundle install`:

```
Installing mysql (2.8.1) from .gem files at /home/mesabeadmin/.bundle/ruby/1.8/cache with native extensions /usr/local/lib/site_ruby/1.8/rubygems/installer.rb:483:in `build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

/usr/bin/ruby1.8 extconf.rb
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lm... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lz... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lsocket... no
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lnsl... yes
checking for mysql_query() in -lmysqlclient... no
checking for main() in -lmygcc... no
checking for mysql_query() in -lmysqlclient... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers.  Check the mkmf.log file for more details.  You may need configuration options.
```

From ~/.bundle/ruby/1.8/gems/mysql-2.8.1/ext/mysql_api/mkmf.log:

```
/usr/bin/ld: cannot find -lmysqlclient
```

**Comment by tommyvernieri** [comment]
I tracked the problem down to a typo in the command I copied from the wiki. I've updated the wiki with the correct package name.

**Comment by Alvarord** [comment]
I have the same problem on Ubuntu 10.10 installing: 

ii  libmysql-ruby1.8                                                          2.8.2-1  

Doesn't solve the problem i installed libmysqlclient-dev and works perfectly.

Thanks a lot.
