### ISSUE TITLE
rendering error dashboard/index.html

### ISSUE THREAD

**Issue by CaqKa** [wesabe/mesabe#11]
I installed mesabe on virtual PC - ubuntu 10.04 desktop. got to the signup page.
then i imported the snapshot. when i want to login with my email i am getting:

terminal windows:
http://dl.dropbox.com/u/1183736/pfc_terminal.txt
http://dl.dropbox.com/u/1183736/brcm_terminal.txt

browser:
Errno::ECONNREFUSED in Dashboard#index

Showing /home/mesabe/wesabe/pfc/app/views/dashboard/index.html.erb where line #21 raised:

Connection refused - connect(2)
Extracted source (around line #21):

18:   jQuery(function(){ page = new wesabe.views.pages.dashboard() });
19: </script>
20: 
21: 
22: <% preload_accounts; preload_credentials; preload_tags %>
Rails.root: /home/mesabe/wesabe/pfc

Application Trace | Framework Trace | Full Trace
lib/service.rb:93:in `get_without_error_handling'
lib/service.rb:72:in`get'
lib/service.rb:25:in `get'
lib/data_preloading.rb:23:in`_preload_url_into'
lib/data_preloading.rb:4:in `preload_accounts'
app/views/dashboard/index.html.erb:21
Request

Parameters:

None
Show session dump

Show env dump

Response

Headers:

None

**Comment by CaqKa** [comment]
i had an error wit brcm.
i forgot to put the password into development.properties. but it still didnt workd....
after that i again made the maven2 points:
mvn install:install-file -Dfile=xmlson-1.5.2.jar -DpomFile=xmlson-1.5.2.pom
mvn install:install-file -Dfile=shore-0.2-SNAPSHOT.jar -DpomFile=shore-0.2-SNAPSHOT.pom

now i have running open wesabe on virtual pc with ubuntu 10.04 desktop.

**Comment by eventualbuddha** [comment]
I've encountered this error too, but refreshing the page usually makes it go away. I don't know why it's doing this yet, but I'll post here if it is fixed.

**Comment by tehj** [comment]
refreshing din't work for me... any other solution?

**Comment by eventualbuddha** [comment]
This seems to depend on which Ruby server you use. The one that made it worst for me was Unicorn. The one that's been the most stable has been (sadly) Webrick. Try webrick/mongrel/thin/unicorn/passenger until you find one that works.
