### ISSUE TITLE
(includes workaround) /opt/wesabe/pfc/lib/importer/wesabe.rb:92in `import_user':undefined method `returning' for #<Importer::Wesabe:0xb6997364> (NoMethodError)

### ISSUE THREAD

**Issue by lofidevops** [wesabe/mesabe#12]
I have been using the importer script to get Mesabe up and running, but stalled at importing our snapshot with the above error.

The command I attempted (from /opt/wesabe/pfc) was: thor snapshot:import /mnt/wesabedata/username.zip (where wesabedata was a mounted shared folder on our Ubuntu Server virtual machine)

To resolve this I had to add the following method to the Wesabe class:

def returning(value)
   yield(value)
   value
end

Any idea why? Has something not installed correctly?

**Comment by meleyal** [comment]
This issue is now fixed, see http://github.com/wesabe/pfc/issues/closed#issue/21

**Comment by lofidevops** [comment]
I downloaded the code after the issue was fixed (as far as I can see) - any idea why it would still be included? I will ask the author of the installation script about whether it can upgrade Mesabe code.

**Comment by meleyal** [comment]
hm, it looks like the same issue. Double check you have the most recent version of pfc (`git pull` in your pfc directory if you downloaded with git)
