### ISSUE TITLE
Unable to download dropbox files

### ISSUE THREAD

**Issue by jacobkdavis** [wesabe/mesabe#26]
It appears that the files hosted on the wesabe / mesabe dropbox are no longer accessible.  There are several requirements specified in the Mesabe DIY wiki:

https://github.com/wesabe/mesabe/wiki/Mesabe-DIY

Under this section:

In your wesabe directory, create a mvn directory, and copy shore-0.2-SNAPSHOT.jar, shore-0.2-SNAPSHOT.pom, xmlson-1.5.2.jar, and xmlson-1.5.2.pom to that directory. Then cd to the mvn directory and install those files with Maven 2 by running:

Example:
http://dl.dropbox.com/u/40652/shore-0.2-SNAPSHOT.jar

These all return a 404 error. Some google-fu hasn't been able to find these anywhere else on the internet either.  

Is there somewhere else I can download these?

**Comment by unclespeedo** [comment]
I pulled down the pre-built VM and managed to retrieve the shore-\* files from the virtual disk, I can share my dropbox folder with you if you'd like. 

It's not a permanent solution but it should get you past this hurdle.

**Comment by zenrook** [comment]
Yes Please share.

**Comment by ghost** [comment]
I also need these files and don't currently have virtual box installed.  Any chance you can share?  Thanks

**Comment by dyad10** [comment]
Also trying to get these files, the virtual machine also seems to be offline, it seems to be getting harder to build this, does anybody still have these files?

**Comment by indirect** [comment]
I've uploaded both files to this project's downloads at https://github.com/wesabe/mesabe/downloads. You can download each file at https://github.com/downloads/wesabe/mesabe/xmlson-1.5.2.jar and https://github.com/downloads/wesabe/mesabe/shore-0.2-SNAPSHOT.jar.

**Comment by stuarteggleston** [comment]
Hi there, I don't suppose you fancy uploading the .pom files to the downloads section too?

I'm trying to get hold of shore-0.2-SNAPSHOT.pom & xmlson-1.5.2.pom

Cheers.

**Comment by indirect** [comment]
@stuarteggleston added to https://github.com/wesabe/mesabe/downloads

**Comment by stuarteggleston** [comment]
Thanks André. I will give them a go!
