### ISSUE TITLE
$ gem install libcharguess-1.0.gem requires sudo

### ISSUE THREAD

**Issue by randomthoughts** [wesabe/mesabe#4]
It's a pretty confusing section, because I think libcharguess needs sudo but meanwhile
$bundle install should not be run under sudo.

(But I'm not sure this time, so I didn't edit the wiki.)

**Comment by geekysage** [comment]
Thanks, I have edited the wiki to reflect this.

**Comment by eventualbuddha** [comment]
You don't need `sudo` if you set `GEM_HOME` to something writable by you. For example, I set mine like this: `GEM_HOME=~/.gem`.
