### ISSUE TITLE
API Included?

### ISSUE THREAD

**Issue by martinpengellyphillips** [wesabe/mesabe#7]
Hi there,

Great job getting this out there. Have got a server set up now and just starting to play about with it a bit. One thing I noticed is that attempting to retrieve http://localhost:3000/accounts.xml just bails with a 500 error whereas on Wesabe's server it correctly returns the account details. 

Are there some extra packages/setup required to get this working? If so, could you point me in the right direction?

ta,

Martin

**Comment by eventualbuddha** [comment]
You should tail the `development.log` while making that request to see what the error is. If it's not something obviously wrong with your setup, please create an issue in the `pfc` project.
