### ISSUE TITLE
Exchange Rate Conversion Throws an Exception - My Accounts/Dashboard keeps trying to load

### ISSUE THREAD

**Issue by geekysage** [wesabe/mesabe#8]
Thanks for creating the nice wiki guide. I did run into some problems (read: RubyGems and Bundler) while setting it up on my Ubuntu 10.0.4 Desktop VM image. But I was able to resolve them and I got Wesabe running at around 3:00 in the night. Imagine my happiness. I went ahead and signed up on the local Wesabe with the same email address as my original Wesabe account, which gave me problems while restoring the snapshot and I had to manually delete the account from the db but that's another story.

After restoring the snapshot, I logged in again. The My Accounts and the Dashboard pages kept trying to load but never finished. Since it was very late, I called it a night. Today, I still have the same issue. The targets are being displayed correctly so I am sure Wesabe is installed properly. The log has this error:

Jul 31, 2010 9:05:24 AM org.eclipse.jetty.util.log.Slf4jLog warn
SEVERE: /v2/accounts/analytics/summaries/monthly/20090801/20100801/USD
com.wesabe.api.util.money.ExchangeRateNotFoundException: Unable to find usable currency exchange rate from INR to USD on 2010-07-29

As you can tell, I have some foreign investment accounts. It seems that Wesabe uses an exchange rate service which is not accessible from my machine. Will appreciate any help with this. If you do not immediately know the solution, please let me know so I can download a snapshot from Wesabe after deleting the investment accounts. Sorry for my long rambling, I just wanted to include all the details :)

By the way, I am going to try and update the Wiki with my findings.

**Comment by geekysage** [comment]
Update: Edited the Wiki.

**Comment by oliverng** [comment]
i am having the exact same issue except from CAD to USD, resulting in load timeouts on some charts and data... everything else seems to be running OK.

SEVERE: The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
com.wesabe.api.util.money.ExchangeRateNotFoundException: Unable to find usable currency exchange rate from CAD to USD on 2010-06-26
    at com.wesabe.api.util.money.CurrencyExchangeRateMap.getExchangeRate(CurrencyExchangeRateMap.java:171)

**Comment by nylen** [comment]
See the readme in the PFC project (http://github.com/wesabe/pfc).  It explains what's going on here.  Worst case, you can do `script/rails console` from your pfc directory and add an exchange rate manually using the Ruby code snippet on that page.

**Comment by geekysage** [comment]
You are a lifesaver, nylen! I added some rows to the currency_exchange_rates table as suggested on the PFC readme and it started working. If you had not replied, I was going to look at the code tonight. Many thanks for pointing me in the right direction!
