### ISSUE TITLE
Confusing order for RubyGems and Bundler instructions

### ISSUE THREAD

**Issue by tommyvernieri** [wesabe/mesabe#9]
Reading through the install instructions for PFC, I thought that I was supposed to install Bundler when it was listed in the "Requires" section. Instead of listing the `gem` command for Bundler there, just leave it out to make it more clear that there are more complete instructions later.

Also, it's not clear when it's OK to exit from `su`.

**Comment by geekysage** [comment]
I agree about not putting install commands in the requires when more things are required than simply executing those commands. I do not know who made that change to the wiki but I will remove the command in the 'Requires' sub-section to avoid confusion and frustration.

**Comment by tommyvernieri** [comment]
Thanks, that should help.
